In [1]:
from os import listdir
books = listdir('./books/')
text = ''
for book in books[:20]:
    with open('books/' + book) as file:
        text += file.read().lower()

In [2]:
max_len = 60
step = 3
sentences = []
next_chars = []

for i in range(0, len(text) - max_len, step):
    sentences.append(text[i:i+max_len])
    next_chars.append(text[i + max_len])

In [3]:
chars = sorted(list(set(text)))
char_index = dict((char, chars.index(char)) for char in chars)

In [4]:
import numpy as np

In [5]:
x = np.zeros((len(sentences), max_len, len(chars)), dtype=np.bool)
y = np.zeros((len(sentences), len(chars)), dtype=np.bool)

for i, sentence in enumerate(sentences):
    for t, char in enumerate(sentence):
        x[i,t,char_index[char]] = 1
    y[i, char_index[next_chars[i]]] = 1

In [9]:
from keras import layers
from keras.models import Sequential

model = Sequential()
model.add(layers.LSTM(128, input_shape=(max_len, len(chars))))
model.add(layers.Dense(len(chars), activation='softmax'))

In [10]:
from keras.optimizers import RMSprop

In [11]:
model.compile(loss='categorical_crossentropy', optimizer=RMSprop(lr=.01))

fit
===

In [12]:
def sample(preds, temperature=1.0):
    preds = np.asanyarray(preds).astype('float64')
    preds = np.log(preds) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    probas = np.random.multinomial(1, preds, 1)
    return np.argmax(probas)

In [13]:
import random

In [15]:
for epoch in range(1, 60):
    print(f'\nepoch - {epoch}')
    model.fit(x, y, batch_size=128, epochs=1)
    start_index = random.randint(0, len(text) - max_len - 1)
    generated_text = text[start_index: start_index + max_len]
    print(f'\n--- Generated with seed:  {generated_text}')
    
    for temperature in [0.2, 0.5, 1.0, 1.2]:
        print(f'\n------ temperature:  {temperature}')
        for i in range(400):
            sampled = np.zeros((1, max_len, len(chars)))
            for t, char in enumerate(generated_text):
                sampled[0, t, char_index[char]] = 1
            
            preds = model.predict(sampled, verbose=False)[0]
            next_index = sample(preds, temperature)
            next_char = chars[next_index]
            
            generated_text += next_char
            generated_text = generated_text[1:]
            print(next_char, end='')

W0821 13:31:35.188743  7808 deprecation.py:323] From C:\Users\Bogdan\Anaconda3\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



epoch - 1


W0821 13:31:35.714260  7808 deprecation_wrapper.py:119] From C:\Users\Bogdan\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/1
121477/121477 [==============================] - 108s 888us/step - loss: 2.5061

--- Generated with seed:  щенником: "рождество твое, христе боже наш..."
вскоре приеха

------ temperature:  0.2
ли в столько постал стая и постал страшной станить не старая от кругой не помостим от ним постал страствое востого столько отеци потом на него стапил от помужить в себя помужит сторой подом не помужит старать старам странный и старал страсный и пот не в ступать и стала в столько блатный и верего помого полужит в стак в ступат и пот в помужит ступать потругой и привели в столько и странный полужим 
------ temperature:  0.5
погорядной немость, то как в потом ни столи стала старенным
потрали в шебе мого по меня ступива поже в пом ступия не за спотили постоля ни двог
у ней встам в столок, будного, не прот нему верьего похожий приплишним
вот. провоком. - сташки в покой и по-мелеч коп-ты была старами, от пот моликов отцугу. на вирего больно его откак не помом ступами и стары и степит мне пол

всё это был возвражал скончий другой похожиты. а он она ты в похожил водоходили его на как спросила стало слова. в похоже похожидел на него две две без после про своим весь воздый про спросте больше.
- не протоде, как не были прочита, анна акимовна была она спит из похожит в образел на знать стало его расставила стороником.
- сполдадно всем барон, сказал он не показал пахне я не ведь за прошлост
------ temperature:  1.0
 день, же дня в ничтренный
в надобрымахина, был у, как матьрый... - оставить.а. изда не - а я следа.
с врезвно он еле, то ей простану. он вскал и ничего водослот.
в засказывала ушта, что если т. говорил помпыня,
и зачима, изям солнце ни смеять... спает винцама еге... - закогрую из его горнет чулственным ци ктраыво.
рахот
равна люблялся, - ниперга вододно без спусл лук, распужная стак п г всем день
------ temperature:  1.2
гие
гвмади, лес. помовки, первать для
на тебе тветрожьстварыша: рассказывая будно бываться знаю, просодесня гропял шагорились на покримивество вами. в

 ы, молодое приыть гизить.
он ру
epoch - 14
Epoch 1/1
121477/121477 [==============================] - 102s 837us/step - loss: 1.6212

--- Generated with seed:  ло
жалко, - с просителями выходил из себя, сердился, бросал 

------ temperature:  0.2
уже на старик под двер и под своей от этого старик с находить и с себя и подледной старик его старая старая старая с получаете же свете на стариках он под нее смеяться с ней видели в карак и с какой
после нем получившной показывать стал не приворона в коровать. в карак не приводя в картанца и приворил с него под нем от этих вас в карань. по кончил с получившийся с какой как не после нет под нем по
------ temperature:  0.5
следние от
головерком. не завел, он пильку всё это не отой воздавала старух!
- спросил он. - сказал и после на пользу не видел как
мерка и при меня и тал пошли сама после старая до после парало по прикалить и дергачие, как бы в образаться и не знакомые поразил своего масла, как не после бедной
завеликновать об к нему на друг

C:\Users\Bogdan\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log
  This is separate from the ipykernel package so we can avoid doing imports until


звмоило, лет и семглечно
лжно были
госьями умла...
припетаная в работомленнозь, парибует.
лицо при ужасой 
epoch - 15
Epoch 1/1
121477/121477 [==============================] - 102s 839us/step - loss: 1.6147

--- Generated with seed:   не вспоминал. а потом и совсем забыли. и
только старуха, ма

------ temperature:  0.2
ленький голове и помнила на свое имениному и под свое стало стали по столу, под нее очень получительно было получили и под нее служил и не понимали по стамовник. на стал и под нем больной получает больно уже не отвечай, которые служил и на столпока. она сказала она, сколько после верена! - сказала она, которые сованая с ним стала по стамовник.
после не водорили и стал по колена и получала стал и с
------ temperature:  0.5
ложали чай, как толпесу не образною поковни, ничего не получил и должно быловое стыд, подпала и присовшество ее смешком.
- думал такое как-то детей же она служит... волков, матери на столповой и служой шалетство была позворовать принимала на какое-то д

 все всем вам сидела посинется в серете стал от неделиком потом и помогала она была старик, что каждый деревни, подушавшись по крастом, но того пристал свобо тысяч обедали в кортентки в избе... водели и не слышате в каросина, как она состоил ее, вотом ли обе недел и попросилась в обедать и поднимание кними из ее после обедать стало подали не нему не
потушка. еще широтством, и выпал и светенила он 
------ temperature:  1.0
пробилокал концу дрожастоми и куплого
, отеуяе. машинела.
 он не опойдет ме! - сегодурь анте-хеих покорщины
матье, подурил тогба выбы, как и думала меня подрагалась на дерогом, во дровится враз, какой лагле собора нашевшись били о
мне поаватерьегостарнуты, -
толда чыхо и стал к отц,еа воодни художные обедатухе.

шами
постусла, - почему-то здуривы, и должности воздел, как не купец, по
далейной день
------ temperature:  1.2
ги носить.
позывал все делать говорить, что, что желешь... и пьяа?
за кродно,
молочность,
подапишной рыгин с
бы. покторил и сказать, за нее открыло


у настечком гое и знаете он убледные любила. так поспевчить
мы
в удоротох и протянство
и окресленно мне десять, рехо те лишки это ты
epoch - 32
Epoch 1/1
121477/121477 [==============================] - 102s 838us/step - loss: 1.5103

--- Generated with seed:  е
слушает баба, уперлась на своем и хоть ты что! "тебя люблю

------ temperature:  0.2
 и привол и с простом, и не меня и служащие стало собак с разобедиться и служаго верхнения. - спросила она, вы состоищенная страшно было привел по стекла, подобро в обедать бы в свое комната были в двужи не мог в ували и служащие столпо страшно и служащие старую долго светлое с ней и спально умальшего в стороне слово под свое от скороктори и под него получаешью и стали собака и протяги и даже стал
------ temperature:  0.5
и на свое кажется с нем обородом, подверка был на боком. - сказал, как бы не призвет не обедо состоичь, как ее когда протягой полосель. он после сверкот протяги и шапочка тоже всё слышная и долго щека и волчата так! он долго с

- который в руки на степан по!
- говорил он.
- да не должно, чтобы
не простой разговара служит, потом савки предлостила советновать, бог он был смутился и забадет 
------ temperature:  1.0
наробение бдавое медь, а
брать и
пнятесла
место ницо не всече, в памя и но
- лаккие
выслушающее глазам и приехал со
воссного церковно, в савой больше игрю, мои ее внучить, -скацел на
любви себя тебе в шлица и по себе блупче...

ахвасилась и этот точно яух, потоме надо!
они удиваемся шуми вздрогнул и она выражома не т
машом в него одравших. приядная, небось
потры, была светило не
жизнесуны
и вом ил
------ temperature:  1.2
и гололок
села на брюцетой; когда и
казалась с недований
одного кургочоленые жальный углазия, самое виняя остался и боа.
в одное знаю и знает, шагодно!
о другиваться...
- тебя решом, бог., любился максими левно онемыеожается леколик.
ты сказала синей, пятся нимами, громко повянутей, а вчеташная, достанку, уже
билет, ориг, артнуехохости! ну мужа темные ; кажино, кудаю
двежности не по

и он собера и спала своиму
состорания. - продолжал он. - сказал он, пока она стал не меня и подобралась на столования и спали на столование по свети и не сказала в страх! - сказала в карали и под нем не не от этой бы получали с просилоста, а сказала и под сторонуха, а а его после получил и свидала своей страшали и под нем на свете и под нем на своими воспительном и последние старик и делали не отв
------ temperature:  0.5
етить обедать совестник.
- закорожку со всем связу, и давала у него доканими. в стераль, а на рыжица подобранная страдая стала не
матери. после покрите с своим пильмую обедать седить пальше, а зачем прелости все убила не спала в него в страгую дома по вереном, я не могу она стал он начала свою дома. я последний советник. - пробежала ее со своей получается и человек с для в обращения и спала на тре
------ temperature:  1.0
тья, земрю, - да, опять свидцать, стра, что ему подержаться не наскал алетво о парку. она платила к скутнего, она, схотреме-то и хотелось, кабаты ан

пертелься известно бываное.
- выскорил
обессвытыми постали и
рабожие. варварушка году! не ходи, давно, когда же котмрейвей не завали и посел и же передмоховый крепевшего стало николаду, называть жизнь, а всё это кошек был чем
------ temperature:  1.2
сте, краснел изфцами обтинетам. -взбожу глаза поставалось, торша закуз сигалье.
.к часговох! сама к узданеему бринер.
конез-истепенник; во, простатнеть. хочу сепал на стало, смугать рог есю, помнит л ищемгнеливо покрыма. испали схвам анна м скужек при дмольно богалора было спратно сидела я отгравяла, тою трас челозл-кворценисты, от ыхади, настолую думал на сказле его, пятьччем проблатнок лиз рабло
epoch - 58
Epoch 1/1
121477/121477 [==============================] - 103s 847us/step - loss: 1.4411

--- Generated with seed:   за талию. - ну-ка, расскажи, мужнина жена! хо-хо... нешто
н

------ temperature:  0.2
е просто все этот в коровию. должный раз показывая старать. она была покорбатка и принимала на сколькому подомельному и с коления. - 

In [16]:
import pickle
pickle.dump(model, open('generation_word_model', 'wb'))

#### взвешивание распределения вероятностей с учетом значения темперартуры

In [1]:
import numpy as np

def distribution(origin, temperature=0.5):
    dis = np.log(origin) / temperature
    dis = np.exp(dis)
    return dis / np.sum(dis)

In [7]:
distribution([0.1, 0.4, 0.5], 0.1)

array([9.24709932e-08, 9.69628642e-02, 9.03037043e-01])

In [3]:
distribution([0.1, 0.4, 0.5], 0.2)

array([2.40963855e-04, 2.46746988e-01, 7.53012048e-01])

In [4]:
distribution([0.1, 0.4, 0.5], 0.5)

array([0.02380952, 0.38095238, 0.5952381 ])

In [5]:
distribution([0.1, 0.4, 0.5], 0.8)

array([0.07075339, 0.40024162, 0.52900499])

In [6]:
distribution([0.1, 0.4, 0.5], 1)

array([0.1, 0.4, 0.5])